#SESABench/Table-3-Parboil/spmv
GN_FLAGS = -I../../parboil/common/include -D_SYM
#GKS_FLAGS = --symbolic-config --max_sym_array_size=2048
#SESA_FLAGS = -scev-aa
TARGET = spmv

include ../../Makefile.common

