#SESABench/Table-3-Parboil/histo/histo_main
GN_FLAGS ?= -I../../../parboil/common/include -D_INTERMEDIATE
#GKS_FLAGS ?= --symbolic-config --max_sym_array_size=2048
#SESA_FLAGS ?= -scev-aa
TARGET = histo_main

include ../../../Makefile.common

