#SESABench/Table-2-Performance-Improve/bitonic-4.3

#interesting -- this one has options for shared size limit of 2^4 through 2^8 -- we'll do the two extremes

GN_FLAGS = -DSHARED_SIZE_LIMIT=16
TARGET = bitonic-4.3_16

include ../../Makefile.common

# GN_FLAGS = -DSHARED_SIZE_LIMIT=256
# TARGET = bitonic-4.3_256

# include ../../Makefile.common
