#SESABench/Table-1-CUDA-5.5/Table-3-Parboil
DIRS := bfs cutcp histo mri-gridding spmv stencil
GKP_FLAGS = --symbolic-config --max-time=7200
GKS_FLAGS = --symbolic-config --max-time=7200
LEVEL = ../../
include ../Makefile.dir.common
