#SESABench/Table-2-Performance-Improve/brentkung

GN_FLAGS = -Drwidth=32 -DBINOP_ADD -DN=32 -D_SYM
GKS_FLAGS = --symbolic-config --race-prune
TARGET = brenthkung_blelloch

include ../../Makefile.common

