#SESABench/Table-3-Parboil/histo/histo_prescan
GN_FLAGS = -I../../../parboil/common/include -D_RESCAN -D_SYM
#GKS_FLAGS = --symbolic-config --max_sym_array_size=2048
SESA_FLAGS = -scev-aa
TARGET = histo_prescan

include ../../../Makefile.common

