#SESABench/LoneStar/apps/bfs/BFS_ATOMIC
GN_FLAGS += -I../../../include -DVARIANT=BFS_ATOMIC -D_SYM
TARGET = BFS_ATOMIC
GKP_FLAGS += --max-sym-array-size=1024 --avoid-oob-check
include ../../../../Makefile.common

