#SESABench/Table-3-Parboil/mri-gridding/mri_reorder
GN_FLAGS = -I../../../parboil/common/include -D_REORDER -D_SYM
#GKS_FLAGS = --symbolic-config --max_sym_array_size=2048
#SESA_FLAGS = -scev-aa
TARGET = mri_reorder

include ../../../Makefile.common

