#SESABench/Table-3-Parboil/bfs
GN_FLAGS = -I../../parboil/common/include -Xptxas -dlcm=cg -D_SYM
GKS_FLAGS = --symbolic-config --max_sym_array_size=2048
SESA_FLAGS = -scev-aa
TARGET = bfs

include ../../Makefile.common

