#SESABench/Table-3-Parboil/bfs
GN_FLAGS = -I../../parboil/common/include -D_SYM 
#remvoved -- these should be nvcc only: -Xptxas -dlcm=cg 
GKS_FLAGS = --symbolic-config --max_sym_array_size=2048
SESA_FLAGS = -scev-aa
TARGET = bfs_prog

include ../../Makefile.common

