#SESABench/Table-3-Parboil/stencil
GN_FLAGS += -I../../parboil/common/include
GKS_FLAGS ?= --symbolic-config --max-time=7200
GKP_FLAGS ?= $(GKS_FLAGS)
#SESA_FLAGS ?= -scev-aa
TARGET = stencil

include ../../Makefile.common

